### DISCUSSION TITLE
custom nodesets

### DISCUSSION THREAD

**Discussion by basyskom-dege** [FreeOpcUa/async-opcua#56] [General]
Hello!

I came across this fork and i am happy to see it being in active development. Regarding the nodeset compiler: is it possible to compile nodesets that depend on other nodesets? The example only did the PROFINET nodeset. I wanted to generate the AutoID nodeset but i did not succeed since there is no BSD and XSD file present. 

Are there any plans to work on this? I think its necessary to support nodesets with dependencies and without BSD files. Thank you!

**Comment by einarmo** [comment]
Depends on what you want to create, we currently require BSD files if you want custom OPC-UA types. The problem is that there is information that simply isn't present in NodeSet2 files that we require. It may be possible to support NodeSet2 files in the future, and error out if we hit any of those cases.

As for dependencies, you have to plumb that yourself, it's not really that hard to do. The code gen config takes a list of targets, you need to generate each file independently, then modify the `extra_header` section in the config to import the required types.

As for the XSD file, you only need that if your NodeSet2 file has XML versions of any of the types it defines. Doesn't look like AutoID has that.

Codegen based on NodeSet2 files is a fairly large effort, so I don't know when that will happen. The current code gen is pretty tightly connected to the types we read from BSD files, and there's some fiddly logic to make everything work correctly.

**Comment by einarmo** [comment]
@basyskom-dege It's now possible to generate types using NodeSet2 files. It's still a bit experimental, so I can't guarantee it will work for you, but it may be worth trying.

**Reply by basyskom-dege** [reply]
Thank you for the quick follow up! I will look into it.

**Comment by basyskom-dege** [comment]
Hey! I tried to generate the autoID nodeset but without luck. A lot of types are not found, Nodeid names are doubled (I think because they are inherited  from DI but with other Nodeids).

Here is my YAML content. Am I missing something? Auto Id has no XSD file...

```
extra_header: |
  // OPCUA for Rust
  // SPDX-License-Identifier: MPL-2.0
  // Copyright (C) 2017-2024 Einar Omang
targets:
  - type: types
    file: Opc.Ua.AutoID.NodeSet2.xml
    output_dir: src/generated/types/autoId
    enums_single_file: true
    structs_single_file: true
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]
  - type: nodes
    file: Opc.Ua.AutoID.NodeSet2.xml
    output_dir: src/generated/nodesetAutoID
    max_nodes_per_file: 100
    types:
      - file: Opc.Ua.Di.Types.xsd
        root_path: crate::generated::types::di
      - file: Opc.Ua.Types.xsd
        root_path: opcua::types
    own_namespaces:
      - "http://opcfoundation.org/UA/AutoID/"
    imported_namespaces:
      - "http://opcfoundation.org/UA/DI/"
      - "http://opcfoundation.org/UA/"
    name: AutoIDNameSpace
    events:
      output_dir: src/generated/events
      dependent_nodesets:
        - file: Opc.Ua.NodeSet2.xml
          import_path: "opcua::core_namespace::events::"
        - file: Opc.Ua.Di.NodeSet2.xml
          import_path: "opcua::core_namespace::events::"
        - file: Opc.Ua.AutoID.NodeSet2.xml
          import_path: "opcua::core_namespace::events::"
      extra_header: |
        #[allow(unused)]
        mod types {
          pub use crate::generated::types::*;
          pub use ::opcua::types::*;
        }
  - type: ids
    file_path: schema/Opc.Ua.AutoID.NodeIds.csv
    output_file: src/generated/autoid_node_ids.rs
  - type: ids
    file_path: schema/Opc.Ua.Di.NodeIds.csv
    output_file: src/generated/di_node_ids.rs

sources:
  - schema
  - ../../schemas/1.05/Opc.Ua.Types.xsd
  - ../../schemas/1.05/Opc.Ua.NodeSet2.xml
```

**Comment by einarmo** [comment]
I'll look into it... It doesn't really surprise me that there are issues.

You will need to generate the types for `DI` as well though, probably.

**Reply by basyskom-dege** [reply]
Thank you! DI worked fine. I included the generated stuff from DI. The errors occur on types from AutoID though

**Comment by einarmo** [comment]
So, I had a look. There's an error caused by a `/` in an ident, but we can handle that. The bigger problem is that the node ID csv file is _terrible_. It has weird duplicates that aren't really correct, and it's missing a ton of nodes.

It also seems like the schema is entirely missing the `DefaultJson` encoding nodes, which isn't optimal. We probably need a way to work around these, though I expect we'll just have to panic if you call them.

The solution to the node ID problem is probably to allow generating types without relying on the node ID enums at all, which is now possible. It's a bit of work, however.

This wasn't as bad as I thought, there's not really that much work necessary to make something that works for this as well. It might take some time before I get to it.

**Comment by einarmo** [comment]
@basyskom-dege I've put together a PR now (#65) which I managed to get to work with AutoID. Before we make a new release I'll document things a bit better, but to make this work you need to do the following:

 - Set `node_ids_from_nodeset: true` on the `autoid` target. You don't need it for DI, which has a proper node ID CSV.
 - Define a few opaque types, we don't currently do codegen for these. I found `CodeTypeDataType`, `NmeaCoordinateString`, and `LocationName`, all of which are just wrappers around `String`. The proper way to do this is:
 
```rust
#[derive(Default, Debug, Clone, PartialEq)]
pub struct CodeTypeDataType(pub UAString);

impl_encoded_as!(
    CodeTypeDataType,
    |v| Ok(CodeTypeDataType(v)),
    |s: &CodeTypeDataType| Ok::<UAString, Error>(s.0.clone()),
    |s: &CodeTypeDataType| s.0.byte_len()
);

impl UaNullable for CodeTypeDataType {
    fn is_ua_null(&self) -> bool {
        self.0.is_null()
    }
}

#[cfg(feature = "xml")]
impl opcua::types::xml::XmlType for CodeTypeDataType {
    const TAG: &'static str = "CodeTypeDataType";
}
```

though if you don't care about _lists_ of XML items, you can also just define them as type aliases:

```rust
type LocationName = UAString;
```

Either way you need to add them to the codegen target for `autoid`:

```
types_import_map:
  LocationName:
    path: "crate::types"
    has_default: true
```

where `path` is the rust path to wherever you put these types.

With that I got it to compile, at least. I didn't end up panicking for the missing JSON encoding IDs, just fall back on the data type ID, which technically is legal.

**Reply by basyskom-dege** [reply]
Thank you for this! Do you mind sharing the YAML for AutoID? I cant get it to work.

**Comment by einarmo** [comment]
```yaml
targets:
  - type: types
    file: Opc.Ua.AutoID.NodeSet2.xml
    output_dir: src/generated/types/autoid
    enums_single_file: true
    structs_single_file: true
    node_ids_from_nodeset: true
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]
    types_import_map:
      CodeTypeDataType:
        path: "crate::types"
        has_default: true
      NmeaCoordinateString:
        path: "crate::types"
        has_default: true
      LocationName:
        path: "crate::types"
        has_default: true
  - type: types
    file: Opc.Ua.Di.NodeSet2.xml
    output_dir: src/generated/types/di
    enums_single_file: true
    structs_single_file: true
    id_path: crate::di_node_ids
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]
  - type: nodes
    file: Opc.Ua.AutoID.NodeSet2.xml
    output_dir: src/generated/node_set_auto_id
    max_nodes_per_file: 100
    types:
      - file: Opc.Ua.Di.Types.xsd
        root_path: crate::generated::types::di
      - file: Opc.Ua.Types.xsd
        root_path: opcua::types
    own_namespaces:
      - "http://opcfoundation.org/UA/AutoID/"
    imported_namespaces:
      - "http://opcfoundation.org/UA/DI/"
      - "http://opcfoundation.org/UA/"
    name: AutoIDNameSpace
    events:
      output_dir: src/generated/events
      dependent_nodesets:
        - file: Opc.Ua.NodeSet2.xml
          import_path: "opcua::core_namespace::events::"
      extra_header: |
        #[allow(unused)]
        mod types {
          pub use crate::generated::types::*;
          pub use ::opcua::types::*;
        }
  - type: ids
    file_path: schema/Opc.Ua.Di.NodeIds.csv
    output_file: src/generated/di_node_ids.rs

sources:
  - schema
  - ../opcua/schemas/1.05/Opc.Ua.Types.xsd
  - ../opcua/schemas/1.05/Opc.Ua.NodeSet2.xml
```

It's pretty close to what you posted above. As you can see I no longer generate IDs for `AutoID` at all.

**Reply by basyskom-dege** [reply]
Thank you! But i still cant get it to compile. I get a lot of errors like `variant or associated item not found in `DataTypeId/ObjectId`` or there are missing nullable trait implementations.

How do I make use of the generated code? The custom-codegen example just uses the generated nodeset, events and types but how do I use di AND autoid? Do I need to generate both and then use them both in the main.rs?

**Reply by einarmo** [reply]
I managed to get the above to compile... Are you getting errors about missing `UaNullable` in the generated code?

There's a generated type in the root of each target which is the main entrypoint. If you want to deserialize messages containing DI/AutoID types on your server or client, you need to add the generated type loader to your server/client implementation. There are methods to do so on the client and on the server builder. See https://github.com/FreeOpcUa/async-opcua/blob/master/samples/custom-codegen/src/main.rs and https://github.com/FreeOpcUa/async-opcua/blob/master/samples/custom-structures-client/src/bin/native_client.rs.

It depends on what you want to do with these types.

As for the generated nodeset, that's used in a `NodeManager` to populate the in-memory address space. Like using `simple_node_manager_imports` and passing Box'd versions of the namespace struct. Again see the `custom-codegen` example I linked above.

**Reply by basyskom-dege** [reply]
Yes I'm aware on how to use this with the NodeManager. I got it to compile now as well. But it panics right after start:
 `thread 'main' panicked at async-opcua-server/src/address_space/mod.rs:219:13:
Namespace index 0 not in address space`

It works fine for DI but i guess i will come back to this later when this is merged in a new release.

But I'm glad you it works without BSD and XSD files! Thank you.

**Comment by evanjs** [comment]
I am curious if others have managed to generate anything re EUROMAP specs using this library

Previously/currently, I am using `locka99/opcua`, but want to eventually transition to using `async-opcua`
However, codegen is one of my big blockers at the moment, to say nothing of utilizing the generated code

Previously, einar helped by making some changes/fixes to the existing codegen in the repository
Issue: https://github.com/FreeOpcUa/async-opcua/issues/29

I wanted to try reaching out to the community before I bug them again

Related [repository](https://github.com/evanjs/opcua-async-rust-euromap-codegen-repro) that I made for the issue

It's been some time since I created that issue, and I've been busy working around other problems in the original repository
Coming back to look at this, I'm hitting a number of errors again
___

Currently I'm just trying to get [EUROMAP83](https://reference.opcfoundation.org/PlasticsRubber/GeneralTypes/v103/docs/) compiling, as that is the standard with the general types

Wanted to make sure I post about my struggles here before I forget in case others have additional input
___
Happy to provide additiona information as needed, but I wanted to be succinct/not totally bomb the thread to start.

**Reply by einarmo** [reply]
I'd recommend you make a new issue if you're still having trouble. I recall that I managed to get this stuff to compile at least, and we've made some quite major improvements to codegen since then.

**Reply by evanjs** [reply]
Thanks @einarmo

I think I got things back into a compiling state
But I wanted to confirm a few things before I open any issues
Or more appropriately for this post, document how I got things working
___
## Codegen Configuration

<details>
<summary><span><code>codegen.yml</code></span></summary>

```yaml
extra_header: |
  // OPCUA for Rust
  // SPDX-License-Identifier: MPL-2.0
  // Copyright (C) 2017-2024 Einar Omang
targets:
  # EUROMAP 83 Types
  # Used by other EUROMAP standards
  - type: types
    file: Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2
    output_dir: src/generated/types/euromap83
    enums_single_file: false
    structs_single_file: false
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]

  # EUROMAP 79 Types
  - type: types
    file: Opc.Ua.PlasticsRubber.ImmToRobot.bsd
    output_dir: src/generated/types/euromap79
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]

  # EUROMAP 83 Node Set
  - type: nodes
    name: EUROMAP83
    file: Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xml
    output_dir: src/generated/nodeset/euromap83
    max_nodes_per_file: 10000
    own_namespaces:
      - "http://opcfoundation.org/UA/PlasticsRubber/GeneralTypes/"
    imported_namespaces:
      - "http://opcfoundation.org/UA/DI/"
      - "http://opcfoundation.org/UA/"

    types:
      - file: Opc.Ua.Types.xsd
        root_path: opcua::types
      - file: Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xsd
        root_path: crate::generated::types::euromap83


  # CORPO Node Set
  - type: nodes
    name: CORPO
    file: Corpo.PlasticsRubber.GeneralTypes.NodeSet2.xml
    output_dir: src/generated/nodeset/corpo
    max_nodes_per_file: 10000
    own_namespaces:
      - "http://corpo.com/nodeset/"
    imported_namespaces:
      - "http://opcfoundation.org/UA/2011/03/UANodeSet.xsd"
      - "http://opcfoundation.org/UA/"
      - "http://opcfoundation.org/UA/DI/"
      - "http://opcfoundation.org/UA/PlasticsRubber/GeneralTypes/"
      - "http://opcfoundation.org/UA/PlasticsRubber/IMM2MES/"

    types:
      - file: Opc.Ua.Types.xsd
        root_path: opcua::types
      - file: Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xsd
        root_path: crate::generated::types::euromap83
      - file: Opc.Ua.PlasticsRubber.ImmToRobot.xsd
        root_path: crate::generated::types::euromap79

  # EUROMAP 83 NodeIDs
  - type: ids
    file_path: EUROMAP/EUROMAP_83/NodeIds.csv
    output_file: src/generated/node_ids/euromap83.rs

  # CORPO NodeIDs
  - type: ids
    file_path: resources/corpo/Corpo.PlasticsRubber.GeneralTypes.NodeSet2.csv
    output_file: src/generated/node_ids/corpo.rs

sources:
  - external\async-opcua\schemas\1.05\Opc.Ua.NodeSet2.xml
  - external\async-opcua\schemas\1.05\Opc.Ua.NodeSet2.Services.xml
  - external\async-opcua\schemas\1.05\Opc.Ua.Types.xsd

  - resources\Opc.Ua.Di.NodeSet2.xml

  - EUROMAP\EUROMAP_83\Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xsd
  - EUROMAP\EUROMAP_83\Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xml
  - EUROMAP\EUROMAP_83\Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.bsd

  - EUROMAP\EUROMAP_79\Opc.Ua.PlasticsRubber.ImmToRobot.xsd
  - EUROMAP\EUROMAP_79\Opc.Ua.PlasticsRubber.ImmToRobot.xml
  - EUROMAP\EUROMAP_79\Opc.Ua.PlasticsRubber.ImmToRobot.bsd

  - resources\corpo\Corpo.PlasticsRubber.GeneralTypes.NodeSet2.xml
  - resources\corpo\Corpo.PlasticsRubber.GeneralTypes.NodeSet2.csv
```

</details>

---
# Missing enum variants for `_Encoding_DefaultJson`

I had to stub `Encoding_DefaultJson` functions

If I understand correctly: We are expected to stub e.g. XML, JSON if either are unsupported by a nodeset
Is this correct?

e.g. [Like this](https://github.com/FreeOpcUa/async-opcua/blob/83d12f0367e3ec250bb90f604338f5f32d641278/samples/custom-structures-client/src/bin/native_client.rs#L132-L134)

```rust
fn full_json_type_id(&self) -> opcua::types::ExpandedNodeId {
    unimplemented!()
}
```
---
# Missing `Default` enums
I needed to add defaults for a few enums
You have noted this before on the issue I opened previously
https://github.com/FreeOpcUa/async-opcua/issues/29#issuecomment-2610906541
> You need a default impl for a few enums. You can just write those yourself, easy.

```rust
// src/generated/types/euromap83/storage_enumeration.rs
// This file was autogenerated from EUROMAP\EUROMAP_83\Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.bsd by async-opcua-codegen
//
// DO NOT EDIT THIS FILE
// ...
impl Default for StorageEnumeration {
  fn default() -> Self {
      Self::PRODUCTION
  }
}
```

While I am able to manually add these after code generation, I am curious if there is a cleaner way to do this
i.e. An idiomatic way to provide these defaults that won't be overwritten by code generation
Especially since we are (ideally) not meant to edit those files by hand

---
# Are BSD files required for type generation?
So, after a bit of head-desking, I was able to get types from my "CORPO" nodeset loaded, so long as I add that node manager first

Though, some of the things I did to get it working definitely felt "off"
e.g. this seems to work (things are compiling)
But it definitely feels weird

Perhaps there is something I can do in `codegen.yml` or elsewhere to reduce hacky-feeling things like this

<details>
<summary><span><code>src/generated/node_ids/mod.rs</code></span></summary>

```rust
mod euromap83;  
mod corpo;  
pub mod corpo_object_type_id {  
    pub use crate::generated::node_ids::corpo::ObjectTypeId::*;  
}  

pub mod DataTypeId {  
    use crate::node_ids::euromap83;  
    pub use euromap83::DataTypeId::*;  
    pub use opcua::types::DataTypeId::*;  
}  

pub mod ObjectId {  
    use crate::node_ids::euromap83;  
    pub use euromap83::ObjectId::*;  
    pub use opcua::types::ObjectId::*;  
}  
  
pub mod ObjectTypeId {  
    use crate::node_ids::euromap83;  
    pub use euromap83::ObjectTypeId::*;  
    pub use opcua::types::ObjectTypeId::*;  
}  

pub mod corpo_data_type_id {  
    pub use crate::generated::node_ids::corpo::DataTypeId::*;  
}  
  
pub mod corpo_object_id {  
    pub use crate::generated::node_ids::corpo::ObjectId::*;  
}  

pub mod corpo_variable_type_id {  
    pub use crate::generated::node_ids::corpo::VariableTypeId::*;  
}  
  
pub mod corpo_variable_id {  
    pub use crate::generated::node_ids::corpo::VariableId::*;  
}
```

</details>


With the above module and this `ServerBuilder` usage, I was _also_ able to load nodes from multiple nodesets

<details>
<summary><span><code>ServerBuilder</code> usage</span></summary>

```rust
let (server, handle) = builder
.with_node_manager(simple_node_manager_imports(
    vec![
        Box::new(opcua::core_namespace::CoreNamespace),
        Box::new(CORPO),
    ],
    "CORPO",
))
.with_node_manager(simple_node_manager_imports(
    vec![
        Box::new(opcua::core_namespace::CoreNamespace),
        Box::new(EUROMAP83),
    ],
    "EUROMAP83",
))
.max_chunk_count(100) // this can help with some clients that are more finicky with buffer size constraints
.trust_client_certs(true)
.port(4840) // standard port for OPCUA server
.with_type_loader(Arc::new(
    euromap83::GeneratedTypeLoader,
))
.build()
.expect("Failed to build server");
```

</details>

That being said, it seems like types can only be generated if I have the BSD file, right?
I am unable to generate the BSD files from UAExpert at the moment, so I only have xml, xsd, Node IDs, etc.

To clarify, I am strictly referring to the generation of typed Rust files for structs, enums, etc.
Like what I have with `euromap83` right now

I can still _use_ and instantiate things in the "CORPO" nodeset (I mostly need this for custom `ObjectTypes` right now)
It just takes a bit more effort

___
## `NodeID` no longer implements `Serialize`
This was minor (in my case), but I had to remove `Serialize`/`Deserialize` from some objects as it appears that `NodeID`s no longer implement `Serialize`/`Deserialize`
#### Before
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExampleStruct {
    pub node_id: NodeId
}
```
#### After
```rust
#[derive(Debug, Clone)]
pub struct ExampleStruct {
    pub node_id: NodeId
}
```

___
# Note
Hopefully there is more I/we can do to help others that need EUROMAP nodeset support with this library
But for this discussion post, I wanted to make sure I record my progress/"solutions"

For other issues I encounter with migration (there are a few), I plan on collating those and opening issues where it makes sense

Thanks again for all the work on this repository
