### DISCUSSION TITLE
methods BadUnsupported

### DISCUSSION THREAD

**Discussion by AiyionPrime** [FreeOpcUa/async-opcua#72] [Q&A] [answered]
I created a server using the ServerBuilder and try to run `add_methods()` from the demo-server sample - while this works fine, I cannot run the methods using uaexpert.
Is this expected behaviour?

Sadly my only output is:
`Call failed with status "BadServiceUnsupported"` in uaexpert.
I do not receive Errors in the log of `cargo run`.

The only thing I see there (but upon browsing of nodes in general) is
`WARN  opcua_server::node_manager::memory::diagnostics] Unknown node...`
occasionally.

Can I somehow raise the loglevel further, or is there a server setting I might have missed?
I did not touch the contents of add_methods.

I'll try to setup an example project of my problem.

**Comment by oroulet** [comment]
logging is not great in that part of the code. so not surprise you do not get any logging.
calling a method on demo server from uaexpert work I suppose?

**Reply by AiyionPrime** [reply]
That's a different story... Building the async-opcua repo fails for me in the fuzzing section...
But I've built a minimal demo repo here:

https://github.com/AiyionPrime/programmatic_methods

**Reply by AiyionPrime** [reply]
I opened an issue for the fuzz problem, but that's not to urgent for me right now :D

**Comment by AiyionPrime** [comment]


**Reply by AiyionPrime** [reply]
I reduced the `server.conf` to this where it still works.

```yml
application_name: OPC UA Sample Server
application_uri: urn:async-opcua-Sample-Server
product_uri: urn:async-opcua-Sample-Server-Testkit
create_sample_keypair: true
certificate_path: own/cert.der
private_key_path: private/private.pem
certificate_validation:
  trust_client_certs: false
  check_time: true
pki_dir: ./pki
# discovery_server_url: opc.tcp://localhost:4840/UADiscovery
tcp_config:
  hello_timeout: 5
  host: localhost
  port: 4855
limits:
performance:
  single_threaded_executor: false
user_tokens:
discovery_urls:
- opc.tcp://localhost:4855/
default_endpoint: null
endpoints:
  none:
    path: /
    security_policy: None
    security_mode: None
    security_level: 0
    password_security_policy: null
    user_token_ids:
    - ANONYMOUS
```
