### ISSUE TITLE
Cannot generate EUROMAP NodeSet

### ISSUE THREAD

**Issue by evanjs** [FreeOpcUa/async-opcua#29]
## Cannot generate EUROMAP NodeSets

✅ generate types for EUROMAP 79, 82.2, 83
🚫 generate NodeSets for EUROMAP 83
___
## Foreword
Please pardon the wall of text, I hope there is at least some helpful information in here

I wanted to persist my thought on using this library before I am fully occupied fixing the OPCUA application that currently utilizes https://github.com/locka99/opcua

There's also a non-zero chance that I am simply not configuring code generation correctly
Knowing how to resolve that would be fine, of course.
___
# Issue Details

Hey guys, thanks for spinning up this fork, I've been meaning to try out the changes for async restructuring, but haven't had a chance.

Currently I am working on a project that is already being deployed but uses the original repository.
Quite a few things needed to be worked around, but I'm excited to see how this library could make things easier for me.

When I was trying the repository out the other day, I noticed that code generation seems to have been reworked and now does a lot more than it did previously.

In my case, I was able to generate types for the EUROMAP specs I have been using.
If I understand correctly, this is a new feature (BSD support) compared to the original repository

However, when attempting to generate nodesets using said types (using documents from the same specifications), the process failed with an XmlError (MissingContent).

As noted in the different design philosophy section of the documentation (under [fork/Different Design Philosophy](https://github.com/FreeOpcUa/rust-opcua/blob/master/docs/fork.md#different-design-philosophy)), it seems that this repository seems to be a bit more focused in a way that the original was not.

My interpretation of this is that we probably don't want to add, say, generated EUROMAP types, etc. directly to this repository in the form of generated code.

In spite of that, I am hoping we can ensure that this library can still be used to generate all (or most, I have no idea what's feasible) OPCUA standards

Or even create a repository for the generated EUROMAP types/nodesets, as suggested in the aforementioned fork document:
> We will not include support for any companion standards, but we are open for changes that make it easier to write extension libraries defining companion standards.
> We may even be open for publishing those libraries from here, just not as part of the main library.

___

## Configuration Details

<details>
<summary><h1>Codegen Configuration</h1></summary>

```yml
extra_header: |
  // OPCUA for Rust
  // SPDX-License-Identifier: MPL-2.0
  // Copyright (C) 2017-2024 Einar Omang
targets:
  - type: types
    file_path: resources/OPCUA/EUROMAP/BSD/Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.bsd
    output_dir: src/generated/types/OPCUA/EUROMAP83
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]
  - type: types
    file_path: resources/OPCUA/EUROMAP/BSD/Opc.Ua.PlasticsRubber.ImmToRobot.bsd
    output_dir: src/generated/types/OPCUA/EUROMAP79
  - type: types
    file_path: resources/OPCUA/EUROMAP/BSD/Opc.Ua.PlasticsRubber.HotRunner.NodeSet2.bsd
    output_dir: src/generated/types/OPCUA/EUROMAP82_2
    extra_header: |
      #![allow(non_camel_case_types)]
      #![allow(clippy::upper_case_acronyms)]

  - type: nodes
    name: EUROMAP83
    file_path: resources/OPCUA/EUROMAP/Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xml
    output_dir: src/generated/nodes/OPCUA/EUROMAP83
    max_nodes_per_file: 10000
    own_namespaces:
      - "http://opcfoundation.org/UA/PlasticsRubber/GeneralTypes/"
      - "http://www.euromap.org/euromap83/"
    imported_namespaces:
      - "http://opcfoundation.org/UA/DI/"
      - "http://opcfoundation.org/UA/"
    types:
      - file_path: resources/OPCUA/EUROMAP/Opc.Ua.PlasticsRubber.IMM2MES.NodeSet2.xsd
        root_path: opcua::types
      - file_path: resources/OPCUA/EUROMAP/Opc.Ua.PlasticsRubber.ImmToRobot.xsd
        root_path: opcua::types
      - file_path: external/rust-opcua/schemas/1.05/Opc.Ua.Types.xsd
        root_path: opcua::types
```

</details>

When I try to generate code using `async-opcua-codegen codegen.yml`, I receive the following message:
```
Error: XML(XmlError { span: 218204..218229, error: MissingContent })
```
___
I wasn't sure how to best debug this error, so I just printed the area within the context of `async-opcua-xml::schema::ua_node_set#load_nodeset2_file`

<details>
<summary><h1>Print snippet</h1></summary>

```diff
diff --git a/async-opcua-xml/src/schema/ua_node_set.rs b/async-opcua-xml/src/schema/ua_node_set.rs
index f9373a6a..197b550a 100644
--- a/async-opcua-xml/src/schema/ua_node_set.rs
+++ b/async-opcua-xml/src/schema/ua_node_set.rs
@@ -28,10 +28,30 @@ pub struct NodeSet2 {

 /// Load a NodeSet2 file from an XML file. `document` is the content of a NodeSet2.xml file.
 pub fn load_nodeset2_file(document: &str) -> Result<NodeSet2, XmlError> {
-    let document = Document::parse(document).map_err(|e| XmlError {
-        span: 0..1,
-        error: crate::error::XmlErrorInner::Xml(e),
-    })?;
+    let head = &document[218204..218229];
+    println!("Attempting to read document: {:#?}", &head);
```

</details>

Running the utility with the above changes returns this message for EUROMAP83
```
Attempting to read document: "<uax:String></uax:String>"
```

When expaning a bit beyond the above span, I do see this, and wonder if it is the problematic element.

<details>
<summary><h2>LastPartId</h2></summary>

```xml
<UAVariable DataType="String" ParentNodeId="ns=1;i=1031" ValueRank="1" NodeId="ns=1;i=6248" ArrayDimensions="1" BrowseName="1:LastPartId">
      <DisplayName>LastPartId</DisplayName>
      <Description>Id(s) of the parts produced in the recently finished cycle</Description>
      <References>
          <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
          <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=1031</Reference>
          <Reference ReferenceType="HasModellingRule">i=80</Reference>
      </References>
      <Value>
          <uax:ListOfString>
              <uax:String></uax:String>
          </uax:ListOfString>
      </Value>
  </UAVariable>
```

</details>

___
# Links
## Official pages for related EUROMAP standards
The following pages provide zip archives containing XML and BSD files for the aforementioned EUROMAP standards

[EUROMAP 79](https://www.euromap.org/euromap79)
[EUROMAP 82](https://www.euromap.org/euromap82)
[EUROMAP 83](https://www.euromap.org/euromap83)

## Potentially related issue from original repository surrounding EUROMAP NodeSet generation
https://github.com/locka99/opcua/issues/46
